[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
    "Cargo.toml"
]
pre_bump_hooks = [
    "cargo check"
]
changelog_file = 'CHANGELOG.md'
changelog_incremental = false
# https://0ver.org/
major_version_zero = true
update_changelog_on_bump = true
annotated_tag = true
gpg_sign = true
version_type = "semver"
